# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20160224_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name2',
            new_name='name',
        ),
    ]
